### ISSUE TITLE
sql scripts should not be installed into sbin

### ISSUE THREAD

**Issue by arhbkb** [dns-stats/hedgehog#22]
The 2.0.0b1 tarball installs "initialise_database.sql" and "insert_lookup_data.sql" into the sbin directory. This isn't really the place for non-executable files. Could you please modify the Makefile to install these into PREFIX/share/hedgehog/sql ?

The hedgehog_database_create.sh script can then read them in from there.

**Comment by saradickinson** [comment]
commit 13423c5fac9087c6e32f58ce1c87aaf367876d3c should do the trick

**Comment by johndickinson** [comment]
Fixed in 2.0.0b2
