### ISSUE TITLE
Install RPostgreSQLHelper

### ISSUE THREAD

**Issue by arhbkb** [dns-stats/hedgehog#23]
The hedgehog installer wants to run:

R CMD INSTALL $(srcdir)/hedgehog/RPostgreSQLHelper

as part of the installation. This works when running "make install" by hand, but breaks packaging. When building an RPM or a DEB of hedgehog, we want the file RPostgrSQLHelper to be installed along with the package (ideally in /usr/share/hedgehog/sql), and then call the R installer in a package post-install script.

Could you please modify the Makefile to install this file somewhere, and *then* call R to install it? This will help packagers.

**Comment by saradickinson** [comment]
Hi, 
Thanks for all the pull requests and issues. At first glance they all look fine - we will try to test/fix all 4 asap, should be sometime this week.  Sara.

**Comment by arhbkb** [comment]
Hi Sara,

Have you had a chance to review my pull requests and issues and commit the changes?

**Comment by saradickinson** [comment]
Not yet - will do it today.

**Comment by saradickinson** [comment]
Hi, 
Please review pull request #24 to make sure it does what you need it to! Sara.

**Comment by saradickinson** [comment]
Hi - updated pull request merged. Hope this fixes it.

**Comment by johndickinson** [comment]
Fixed in 2.0.0b2
