### ISSUE TITLE
hedgehog_conf_read.sh makes a false assumption

### ISSUE THREAD

**Issue by arhbkb** [dns-stats/hedgehog#26]
The script hedgehog_conf_read.sh is making a wrong assumption about YAML syntax. YAML syntax allows for any amount of white space, but this script assumes that indentation will only be 2 spaces. This broke things for me, because my default indent is 4 spaces.

This script is therefore fragile, because anyone editing a YAML file should be able to use any amount of indentation, as allowed by the YAML specification.

**Comment by johndickinson** [comment]
commit 8cd357d878756be694c9492f2a228bc9cc85ef28 should fix this. It uses the perl YAML::Tiny module instead of sed and awk

**Comment by arhbkb** [comment]
\o/

**Comment by johndickinson** [comment]
Fixed in 2.0.0b2
