### ISSUE TITLE
-D not working for hedgehog_rssac_generate_reports.sh

### ISSUE THREAD

**Issue by arhbkb** [dns-stats/hedgehog#36]
I ran the hedgehog_rssac_generate_reports.sh script with -D so that old XML files could be removed. However, it doesn't appear to do anything.

**Comment by saradickinson** [comment]
Hi Anand, 

The -D option is actually an option to remove data from the database, not clean up the xml files (I'll improve the usage description...).

The unique sources is process in a somewhat complicated fashion. We accumulate the raw data into one table in the database as we need to have all the raw data for a 24 hour period before we can produce a RSSAC report. But this data can be huge, for example for ICANN it can contain 7 million rows per day.  When the script is run to summarise this the result is simply 3 numbers, which we write into a separate table and which is used to generate the plot on the front end and the RSSAC yaml. The -D option is to remove the raw data from the database when the script is run. The other option is not to use -D and instead to use the hedgehog_rssac_rm_old_unique_source_data.sh script to clean out the old (raw) data periodically.  This approach works for ICANN as they run the RSSAC reports 1 week after the reporting date to make sure all nodes have uploaded the data for the specified date. 

I can see that for other operators if the raw data isn't that big that this 2 stage approach is overcomplicated.... We have a task planned to review this workflow for the 2.1 next release so please let me know any feedback you have.

**Comment by arhbkb** [comment]
Ah, now I understand. I thought the -D flag was to remove the raw .XML files. So then I have some questions:

1. Once the dsc-extractor has processed .XML files and moved them into the "done" directory, can I just discard them?

2. If I also follow the ICANN model and generate the rssac reports from 7 days ago, can I safely use the -D flag, so that the postgresql database doesn't grow too big? I prefer not to have to run two different scripts, and I like the -D flag, so that old data is discarded from the postgresql database once the script has run.

**Comment by saradickinson** [comment]
1. Yes you can discard them. Unless you want to archive them in case you ever want to use them to re-create the database. (For example, you could archive all the xml and then not backup the database directly as you could always re-create it.) If you wanted to archive them then you can use the hedgehog_datafiles_tar_old_xml_files.sh script to do this. (Note: we are about to change this to put the resulting tar file in a more logical location). 

2. Yes, you should be able to do that. 

I tried to put some additional information on the scripts in the Tools Guide and User Guide here:
https://github.com/dns-stats/hedgehog/wiki/Documentation
These pdfs are also in the 'doc' dir in the HH source.

**Comment by arhbkb** [comment]
I've discovered another bug. If I run "hedgehog_rssac_generate_reports.sh -D" (without using the -s option for a specific day), then here's what happens:

1. On line 34, INPUT_START is set to an empty string
2. On line 53, there is no -s option, so INPUT_START remains empty
3. On line 68, INPUT_START is empty, so the if...then test is skipped
4. On line 102, the following happens:

hedgehog_rssac_process_unique_source_data.sh -s ${INPUT_START} ${DELETE_RAW_DATA_FLAG}

which expands to:

hedgehog_rssac_process_unique_source_data.sh -s -D

Note that the -s option now has the value "-D", and this causes errors in the resulting SQL statement to actually delete data. No data actually gets deleted, and I get a bunch of errors on my terminal.

**Comment by saradickinson** [comment]
Eew. 
1) line 102 should use $START...
2) There is a check that the date is valid, but the 'date' function seems to think -D is a valid representation of today!! 
Will fix.

**Comment by saradickinson** [comment]
https://github.com/dns-stats/hedgehog/commit/3f4baed4c3abbfb8ca0a7d8eba4906063ebdb310
 should fix this

**Comment by johndickinson** [comment]
Fixed in 2.0.0b2
